/* =========================================================================
   TRUST COMPONENTS
   =========================================================================
   The single place the product decides how a KIND of statement is presented.
   Screens never hand-roll a provenance badge, because the moment two screens
   describe a platform assumption differently, the customer stops being able to
   trust either of them.

   Everything here RENDERS backend state. Nothing decides it: no component
   promotes an eligibility, softens a staleness, computes a support level, or
   turns an assumption into a fact.
   ========================================================================= */
import type { ReactNode } from 'react'

/* ------------------------------------------------------------ provenance -- */

export type ProvenanceKind =
  | 'calculated'
  | 'governed'
  | 'user'
  | 'assumption'
  | 'ai'

const PROVENANCE: Record<ProvenanceKind, { glyph: string; label: string; title: string }> = {
  calculated: {
    glyph: '▪',
    label: 'Calculated',
    title: 'Computed by the Onyx tax engine from your recorded facts and governed tax data.',
  },
  governed: {
    glyph: '§',
    label: 'Governed source',
    title: 'Taken from a published, version-controlled tax source.',
  },
  user: {
    glyph: '✎',
    label: 'You provided',
    title: 'A fact you entered. Onyx uses it as stated.',
  },
  assumption: {
    glyph: '~',
    label: 'Assumption',
    title: 'A value assumed for modelling. Confirm it before acting.',
  },
  ai: {
    glyph: '✦',
    label: 'AI explanation',
    title:
      'Wording generated by a language model from figures Onyx already calculated. It does not decide any amount.',
  },
}

export function Provenance({
  kind,
  label,
}: {
  kind: ProvenanceKind
  label?: string
}) {
  const meta = PROVENANCE[kind]
  return (
    <span className={`prov prov--${kind}`} title={meta.title}>
      <span className="prov__glyph" aria-hidden="true">
        {meta.glyph}
      </span>
      {label ?? meta.label}
    </span>
  )
}

/* ------------------------------------------------------------ assumptions -- */

/** The backend's closed certainty vocabulary. The UI must not invent a fifth. */
export type AssumptionCertainty =
  | 'statutory_known'
  | 'user_asserted'
  | 'platform_default'
  | 'derived_from_data'

export interface AssumptionLike {
  assumption_code: string
  certainty?: string | null
  source?: string | null
  value_number?: string | number | null
  note?: string | null
}

/**
 * How each certainty is allowed to be SPOKEN ABOUT.
 *
 * The `platform_default` wording is the one that matters most and it is the
 * reason this map exists at all. When the backend says a contribution-room
 * figure is a platform default, the product must NOT tell the customer they
 * have that much room — nobody checked. It says the model assumed it and that
 * the real figure needs confirming. Saying anything stronger would turn an
 * assumption into a fact the customer might act on.
 */
const CERTAINTY_COPY: Record<
  AssumptionCertainty,
  { badge: ProvenanceKind; term: string; describe: (value: string | null) => string }
> = {
  statutory_known: {
    badge: 'governed',
    term: 'Published limit',
    describe: (v) =>
      v
        ? `This uses the published limit of ${v}.`
        : 'This uses a published statutory limit.',
  },
  user_asserted: {
    badge: 'user',
    term: 'You stated this',
    describe: (v) =>
      v ? `This uses the ${v} you told us.` : 'This uses a figure you told us.',
  },
  platform_default: {
    badge: 'assumption',
    term: 'Assumed by Onyx',
    describe: (v) =>
      v
        ? `This model assumes ${v} is available. Onyx has not verified that figure — confirm your actual amount before acting on it.`
        : 'This model assumes the amount is available. Onyx has not verified it — confirm before acting.',
  },
  derived_from_data: {
    badge: 'calculated',
    term: 'Derived from your records',
    describe: (v) =>
      v
        ? `${v} was derived from the records you have given Onyx.`
        : 'This was derived from the records you have given Onyx.',
  },
}

function certaintyOf(value: string | null | undefined): AssumptionCertainty {
  return value && value in CERTAINTY_COPY
    ? (value as AssumptionCertainty)
    : 'platform_default' // The most cautious reading wins when it is unclear.
}

export function AssumptionNote({
  assumption,
  formattedValue,
}: {
  assumption: AssumptionLike
  formattedValue?: string | null
}) {
  const certainty = certaintyOf(assumption.certainty)
  const copy = CERTAINTY_COPY[certainty]
  return (
    <div className="stack stack-2">
      <div className="row row-2 wrap">
        <Provenance kind={copy.badge} label={copy.term} />
        <span className="text-xs text-muted">
          {humanizeCode(assumption.assumption_code)}
        </span>
      </div>
      <p className="text-sm text-secondary">
        {assumption.note ?? copy.describe(formattedValue ?? null)}
      </p>
    </div>
  )
}

/** CONTRIBUTION_ROOM_AVAILABLE → "Contribution room available". A label
 *  transform only — it never changes which code the backend sent. */
export function humanizeCode(code: string): string {
  const words = code.replace(/_/g, ' ').toLowerCase()
  return words.charAt(0).toUpperCase() + words.slice(1)
}

/* -------------------------------------------------- freshness ≠ integrity -- */

export type FreshnessStatus = 'current' | 'stale' | 'superseded' | 'unknown'

const FRESHNESS: Record<
  FreshnessStatus,
  { tone: string; label: string; help: string }
> = {
  current: {
    tone: 'ready',
    label: 'Current',
    help: 'Nothing Onyx knows about has changed since this was produced.',
  },
  stale: {
    tone: 'attention',
    label: 'May be out of date',
    help: 'Newer information exists. Re-run to get a statement about today.',
  },
  superseded: {
    tone: 'neutral',
    label: 'Superseded',
    help: 'A newer result replaces this one. This is the historical version.',
  },
  unknown: {
    tone: 'neutral',
    label: 'Not evaluated',
    help: 'Freshness has not been evaluated for this result.',
  },
}

export function FreshnessBadge({ status }: { status: string | null | undefined }) {
  const key: FreshnessStatus =
    status && status in FRESHNESS ? (status as FreshnessStatus) : 'unknown'
  const meta = FRESHNESS[key]
  return (
    <span className={`status status--${meta.tone}`} title={meta.help}>
      {meta.label}
    </span>
  )
}

export type IntegrityState =
  | 'verified'
  | 'non_reproducible'
  | 'unavailable'
  | 'legacy_unverifiable'
  | 'not_checked'

const INTEGRITY: Record<
  IntegrityState,
  { tone: string; label: string; help: string }
> = {
  verified: {
    tone: 'ready',
    label: 'Reproduced',
    help: 'This sealed result was re-run from its own pinned inputs and matched. That is a statement about reproducibility, not about tax correctness.',
  },
  non_reproducible: {
    tone: 'blocked',
    label: 'Did not reproduce',
    help: 'Re-running this sealed result from its pinned inputs produced a different identity. Treat the figures with caution.',
  },
  unavailable: {
    tone: 'neutral',
    label: 'Could not be checked',
    help: 'A pinned input is unavailable, so nothing was compared. This says nothing bad about the result itself.',
  },
  legacy_unverifiable: {
    tone: 'neutral',
    label: 'Predates verification',
    help: 'This result was produced before Onyx recorded what a replay needs. Re-run to get a verifiable one.',
  },
  not_checked: {
    tone: 'neutral',
    label: 'Not checked yet',
    help: 'Replay verification has not run for this result.',
  },
}

export function IntegrityBadge({ state }: { state: string | null | undefined }) {
  const key: IntegrityState =
    state && state in INTEGRITY ? (state as IntegrityState) : 'not_checked'
  const meta = INTEGRITY[key]
  return (
    <span className={`status status--${meta.tone}`} title={meta.help}>
      {meta.label}
    </span>
  )
}

/**
 * The two together, always labelled, never merged.
 *
 * Merging them into a single green "verified" tick is the exact mistake this
 * component exists to make impossible: it would tell a customer that a figure
 * which is reproducible is also still true today, and those are different
 * claims.
 */
export function TrustPair({
  freshness,
  integrity,
}: {
  freshness: string | null | undefined
  integrity: string | null | undefined
}) {
  return (
    <div className="trust-pair">
      <div className="trust-pair__item">
        <span className="trust-pair__label">Still current?</span>
        <FreshnessBadge status={freshness} />
      </div>
      <div className="trust-pair__item">
        <span className="trust-pair__label">Reproducible?</span>
        <IntegrityBadge state={integrity} />
      </div>
    </div>
  )
}

/* --------------------------------------------------------- support signal -- */

export interface SupportLike {
  display_support_score?: string | number | null
  support_cap_applied?: boolean | null
  support_cap_reason_code?: string | null
  disclaimer?: string | null
}

/**
 * Support is rendered as four discrete segments and a WORD, never as
 * "83% confidence".
 *
 * The backend is explicit that this is a support/reliability score and NOT a
 * probability that the CRA accepts a claim. A percentage presentation would
 * state exactly that forbidden meaning no matter what caption sat beneath it,
 * so the percentage never reaches the screen.
 */
export function SupportSignal({ support }: { support: SupportLike | null | undefined }) {
  if (!support || support.display_support_score === null || support.display_support_score === undefined) {
    return null
  }
  const score = Number(support.display_support_score)
  if (!Number.isFinite(score)) return null

  const filled = score >= 75 ? 4 : score >= 50 ? 3 : score >= 25 ? 2 : 1
  const word =
    filled === 4
      ? 'Well supported'
      : filled === 3
        ? 'Supported'
        : filled === 2
          ? 'Partly supported'
          : 'Weakly supported'

  return (
    <div className="support">
      <span className="eyebrow">How well supported</span>
      <div
        className="support__track"
        role="img"
        aria-label={`${word}: ${filled} of 4 support segments`}
      >
        {[0, 1, 2, 3].map((i) => (
          <span
            key={i}
            className={`support__seg${i < filled ? ' support__seg--on' : ''}`}
          />
        ))}
      </div>
      <span className="support__word">{word}</span>
      {support.support_cap_applied ? (
        <span className="support__cap">
          Limited because assumptions were involved
          {support.support_cap_reason_code
            ? ` (${humanizeCode(support.support_cap_reason_code)})`
            : ''}
          .
        </span>
      ) : null}
      <p className="support__note">
        This reflects how much evidence and governed data stand behind the
        figure. It is not a prediction that the CRA will accept a claim.
      </p>
    </div>
  )
}

/* ------------------------------------------------------------ eligibility -- */

const ELIGIBILITY: Record<string, { tone: string; label: string; help: string }> = {
  eligible: {
    tone: 'ready',
    label: 'Appears to apply',
    help: 'The governed rules evaluated your recorded facts and this applies.',
  },
  conditionally_eligible: {
    tone: 'attention',
    label: 'May apply, with conditions',
    help: 'This applies only if the listed conditions are met.',
  },
  ineligible: {
    tone: 'excluded',
    label: 'Does not apply',
    help: 'The governed rules determined this does not apply to your situation.',
  },
  indeterminate: {
    tone: 'neutral',
    label: 'Not determined',
    help: 'There was not enough information to determine this either way.',
  },
}

/** Renders the backend's eligibility verdict verbatim. There is deliberately no
 *  path here that upgrades "indeterminate" or "conditionally_eligible" into an
 *  affirmative — the frontend may not improve on a governed determination. */
export function EligibilityBadge({ status }: { status: string | null | undefined }) {
  const meta = (status && ELIGIBILITY[status]) || ELIGIBILITY['indeterminate']!
  return (
    <span className={`status status--${meta.tone}`} title={meta.help}>
      {meta.label}
    </span>
  )
}

/* --------------------------------------------------------- AI explanation -- */

export interface ExplanationOutput {
  summary: string
  why_this_result?: string | null
  why_this_applies?: string | null
  estimated_effect_explanation?: string | null
  what_you_can_do?: { action_ref: string; description: string }[]
  required_cash_or_resource?: string | null
  what_you_need?: string[]
  important_assumptions?: {
    assumption_code: string
    source: string
    certainty: string
    note: string
  }[]
  constraints_and_exclusions?: string | null
  what_changed?: string | null
  freshness_notice?: string | null
  limitations: string
  citation_refs?: string[]
}

/**
 * AI prose, framed so it can never be mistaken for a calculated field.
 *
 * Rendered as PLAIN TEXT into React children — never through
 * `dangerouslySetInnerHTML`. Model output is untrusted content by definition,
 * and React's default escaping is the protection; there is no sanitiser to
 * misconfigure because there is no HTML path at all.
 *
 * `renderer_mode` is intentionally NOT surfaced as a warning. When the
 * deterministic renderer answers instead of a model, the customer is reading a
 * perfectly good explanation and the product says nothing about plumbing.
 */
export function AiExplanation({
  explanation,
  children,
}: {
  explanation: ExplanationOutput
  children?: ReactNode
}) {
  const sections: { heading: string; body: string }[] = []
  const push = (heading: string, body?: string | null) => {
    if (body && body.trim()) sections.push({ heading, body })
  }
  push('Why this result', explanation.why_this_result)
  push('Why this applies', explanation.why_this_applies)
  push('Estimated effect', explanation.estimated_effect_explanation)
  push('What it requires', explanation.required_cash_or_resource)
  push('Constraints', explanation.constraints_and_exclusions)
  push('What changed', explanation.what_changed)

  return (
    <section className="ai-block" aria-labelledby="ai-explanation-label">
      <h3 className="ai-block__label" id="ai-explanation-label">
        <span aria-hidden="true">✦</span> AI explanation
      </h3>
      <div className="ai-block__body">
        <p>{explanation.summary}</p>
        {sections.map((section) => (
          <div className="ai-block__section" key={section.heading}>
            <div className="ai-block__heading">{section.heading}</div>
            <p>{section.body}</p>
          </div>
        ))}
        {explanation.freshness_notice ? (
          <div className="ai-block__section">
            <div className="ai-block__heading">Currency</div>
            <p>{explanation.freshness_notice}</p>
          </div>
        ) : null}
      </div>

      {explanation.important_assumptions && explanation.important_assumptions.length > 0 ? (
        <div className="ai-block__section stack stack-3">
          <div className="ai-block__heading">Assumptions behind this</div>
          {explanation.important_assumptions.map((assumption) => (
            <AssumptionNote key={assumption.assumption_code} assumption={assumption} />
          ))}
        </div>
      ) : null}

      {children}

      <p className="ai-block__note">
        Written by a language model from figures Onyx had already calculated. It
        does not decide any amount, eligibility, deadline or source, and its
        wording is checked against those figures before you see it.{' '}
        {explanation.limitations}
      </p>
    </section>
  )
}
